# Generated by Django 2.0.5 on 2018-05-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ISBN',
            field=models.IntegerField(default=0, verbose_name='ISBN'),
        ),
    ]
