# Generated by Django 2.0.5 on 2018-06-11 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='isbnbook',
            name='typename',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='book.BookType', verbose_name='类型'),
        ),
    ]
