# Generated by Django 2.0 on 2018-04-22 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='typename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookType', to='book.BookType', verbose_name='标签'),
        ),
    ]
