# Generated by Django 2.0.5 on 2018-05-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.CharField(default=0, max_length=14, verbose_name='ISBN'),
        ),
    ]
