# Generated by Django 2.0.5 on 2018-06-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20180529_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='ISBNBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(default=0, max_length=14, verbose_name='ISBN')),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='owner',
            field=models.CharField(choices=[('DD', '当当图书'), ('TB', '淘宝图书'), ('JD', '京东图书')], default='当当书城', max_length=255, verbose_name='所属书城'),
        ),
        migrations.AddField(
            model_name='isbnbook',
            name='Books',
            field=models.ManyToManyField(to='book.Book', verbose_name='书籍'),
        ),
    ]
