# Generated by Django 2.0.5 on 2018-06-10 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20180610_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='isbnbook',
            name='title',
            field=models.CharField(default='暂无', max_length=255, verbose_name='标题'),
        ),
    ]
