# Generated by Django 2.0.5 on 2018-06-20 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0001_initial'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_time', models.DateTimeField(auto_now=True, verbose_name='收藏时间')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.ISBNBook', verbose_name='书籍id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.User', verbose_name='用户id')),
            ],
            options={
                'verbose_name': '购物车',
                'verbose_name_plural': '购物车',
            },
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('user', 'book')},
        ),
    ]
