# Generated by Django 2.0.5 on 2018-06-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20180620_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='cart_time',
            field=models.DateTimeField(auto_now=True, verbose_name='收藏时间'),
        ),
    ]
