# Generated by Django 2.0 on 2018-04-15 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='user',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
    ]
