# Generated by Django 2.0.5 on 2018-06-10 14:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0004_auto_20180610_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('share_time', models.DateTimeField(auto_now=True, verbose_name='分享时间')),
                ('share_text', models.CharField(max_length=200, verbose_name='分享词')),
                ('like', models.IntegerField(default=0, verbose_name='点赞数')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='book.Book', verbose_name='分享书籍')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='分享用户')),
            ],
        ),
    ]
